/** 'waiting': not acknowledged yet, kept on this device until the recipient shows up (see MeshService). */
export type MessageStatus = 'sending' | 'sent' | 'waiting' | 'delivered' | 'failed';
export type MessageDirection = 'in' | 'out';
export type ConversationType = 'dm';

export interface ChatMessage {
  /** UUID generated by the author – globally unique, used to drop duplicates. */
  id: string;
  conversationId: string;
  senderId: string;
  senderNick: string;
  text: string;
  /** Author's timestamp (ms). */
  timestamp: number;
  status: MessageStatus;
  direction: MessageDirection;
  /** 1 once the recipient acknowledged. */
  deliveredCount: number;
  /** Hops travelled (incoming only). */
  hops: number | null;
  /** Office name from the sender's certificate, if the sender was a certified authority on receipt. */
  authority: string | null;
}

export interface Conversation {
  /** "dm:<nodeId>" */
  id: string;
  type: ConversationType;
  title: string;
  /** DM counterpart node id. */
  peerId: string | null;
  createdAt: number;
  lastMessageAt: number;
  lastMessagePreview: string;
  unread: number;
}

/** What this device remembers about another node (stored in the encrypted database). */
export interface Contact {
  nodeId: string;
  /** X25519 box public key (base64), learned from the node's signed packets. */
  boxKey: string | null;
  nick: string;
  /** When the user confirmed this node's key in person (QR / fingerprint); null = unverified. */
  verifiedAt: number | null;
  /** Authority certificate last presented by the node. */
  cert: string | null;
  firstSeen: number;
}

export const dmConversationId = (nodeId: string) => `dm:${nodeId}`;
